INVALID_COMMAND = 'INVALID COMMAND'
ROOT_PATH = f'{__file__}/../..'
SSD_FILE_PATH = f'{ROOT_PATH}/virtual_ssd_pkg/ssd.py'
NAND_FILE_PATH = f'{ROOT_PATH}/nand.txt'
RESULT_FILE_PATH = f'{ROOT_PATH}/result.txt'
MIN_LBA = 0
MAX_LBA = 99
MIN_SIZE = 1
MAX_SIZE = 10